import type {
  UserProfile,
  Notification,
  Conversation,
  SkillAssessment,
  SkillRoadmap,
  UserRoadmapProgress,
} from "@/types"

// Enhanced mock users with different roles and comprehensive data
export const mockUsers: UserProfile[] = [
  // Admin Users
  {
    id: "admin-1",
    name: "Admin Sarah",
    email: "admin@skillxchange.com",
    role: "admin",
    location: "San Francisco, CA",
    avatar: "/placeholder.svg?height=60&width=60",
    skillsOffered: ["Platform Management", "User Support", "Content Moderation"],
    skillsWanted: [],
    rating: 5.0,
    availability: "24/7",
    isPublic: false,
    isOnline: true,
    lastSeen: "now",
    bio: "Platform administrator ensuring smooth operations and user safety.",
    completedSwaps: 0,
    joinedDate: "2022-01-01",
    badges: ["Admin", "Platform Creator"],
    isVerified: true,
    level: "expert",
  },
  {
    id: "admin-2",
    name: "Tech Admin Mike",
    email: "tech.admin@skillxchange.com",
    role: "admin",
    location: "Seattle, WA",
    avatar: "/placeholder.svg?height=60&width=60",
    skillsOffered: ["System Architecture", "DevOps", "Security"],
    skillsWanted: [],
    rating: 5.0,
    availability: "business hours",
    isPublic: false,
    isOnline: true,
    lastSeen: "5 minutes ago",
    bio: "Technical administrator maintaining platform infrastructure and security.",
    completedSwaps: 0,
    joinedDate: "2022-01-01",
    badges: ["Admin", "Security Expert"],
    isVerified: true,
    level: "expert",
  },

  // Moderator Users
  {
    id: "mod-1",
    name: "Moderator Jenny",
    email: "jenny.mod@skillxchange.com",
    role: "moderator",
    location: "Austin, TX",
    avatar: "/placeholder.svg?height=60&width=60",
    skillsOffered: ["Community Management", "Conflict Resolution", "Teaching"],
    skillsWanted: ["Advanced Psychology", "Leadership"],
    rating: 4.9,
    availability: "weekdays",
    isPublic: true,
    isOnline: true,
    lastSeen: "now",
    bio: "Community moderator helping maintain a positive learning environment.",
    completedSwaps: 15,
    joinedDate: "2022-06-15",
    badges: ["Moderator", "Community Helper", "Verified"],
    isVerified: true,
    level: "advanced",
  },

  // Expert Level Users
  {
    id: "expert-1",
    name: "Dr. Emily Watson",
    email: "emily.watson@email.com",
    role: "user",
    location: "Boston, MA",
    avatar: "/placeholder.svg?height=60&width=60",
    skillsOffered: ["Machine Learning", "Data Science", "Python", "R", "Statistics"],
    skillsWanted: ["Web Development", "React"],
    rating: 4.9,
    availability: "evenings",
    isPublic: true,
    isOnline: false,
    lastSeen: "1 hour ago",
    bio: "PhD in Computer Science with 10+ years in AI/ML. Love teaching complex concepts simply.",
    completedSwaps: 47,
    joinedDate: "2022-03-10",
    badges: ["Expert", "PhD", "Top Contributor", "Verified"],
    matchScore: 98,
    isVerified: true,
    level: "expert",
  },
  {
    id: "expert-2",
    name: "Marcus Chen",
    email: "marcus.chen@email.com",
    role: "user",
    location: "San Francisco, CA",
    avatar: "/placeholder.svg?height=60&width=60",
    skillsOffered: ["System Design", "Kubernetes", "AWS", "DevOps", "Microservices"],
    skillsWanted: ["UI/UX Design", "Product Management"],
    rating: 4.8,
    availability: "weekends",
    isPublic: true,
    isOnline: true,
    lastSeen: "now",
    bio: "Senior Software Architect at tech startup. Passionate about scalable systems and mentoring.",
    completedSwaps: 52,
    joinedDate: "2022-02-20",
    badges: ["Expert", "System Architect", "Mentor", "Verified"],
    matchScore: 95,
    isVerified: true,
    level: "expert",
  },

  // Advanced Level Users
  {
    id: "advanced-1",
    name: "Sarah Rodriguez",
    email: "sarah.rodriguez@email.com",
    role: "user",
    location: "New York, NY",
    avatar: "/placeholder.svg?height=60&width=60",
    skillsOffered: ["Graphic Design", "UI/UX Design", "Figma", "Adobe Creative Suite"],
    skillsWanted: ["React", "TypeScript", "Frontend Development"],
    rating: 4.7,
    availability: "evenings",
    isPublic: true,
    isOnline: false,
    lastSeen: "2 hours ago",
    bio: "Creative designer with 6 years experience. Love creating beautiful, user-friendly interfaces.",
    completedSwaps: 31,
    joinedDate: "2022-11-20",
    badges: ["Design Expert", "Mentor", "Verified"],
    matchScore: 92,
    isVerified: true,
    level: "advanced",
  },
  {
    id: "advanced-2",
    name: "Alex Thompson",
    email: "alex.thompson@email.com",
    role: "user",
    location: "Toronto, CA",
    avatar: "/placeholder.svg?height=60&width=60",
    skillsOffered: ["Digital Marketing", "SEO", "Content Strategy", "Social Media"],
    skillsWanted: ["Data Analytics", "Python", "Google Analytics"],
    rating: 4.6,
    availability: "flexible",
    isPublic: true,
    isOnline: true,
    lastSeen: "30 minutes ago",
    bio: "Digital marketing specialist helping businesses grow online. Always learning new tools!",
    completedSwaps: 28,
    joinedDate: "2023-01-08",
    badges: ["Marketing Pro", "Content Creator", "Verified"],
    matchScore: 88,
    isVerified: true,
    level: "advanced",
  },

  // Intermediate Level Users
  {
    id: "intermediate-1",
    name: "Jamie Park",
    email: "jamie.park@email.com",
    role: "user",
    location: "Los Angeles, CA",
    avatar: "/placeholder.svg?height=60&width=60",
    skillsOffered: ["JavaScript", "Node.js", "HTML/CSS"],
    skillsWanted: ["React", "Database Design", "AWS"],
    rating: 4.4,
    availability: "weekends",
    isPublic: true,
    isOnline: true,
    lastSeen: "now",
    bio: "Full-stack developer with 2 years experience. Eager to learn and share knowledge!",
    completedSwaps: 18,
    joinedDate: "2023-03-15",
    badges: ["Rising Star", "JavaScript Developer"],
    matchScore: 85,
    isVerified: false,
    level: "intermediate",
  },
  {
    id: "intermediate-2",
    name: "Lisa Kim",
    email: "lisa.kim@email.com",
    role: "user",
    location: "Chicago, IL",
    avatar: "/placeholder.svg?height=60&width=60",
    skillsOffered: ["Photography", "Photo Editing", "Lightroom", "Portrait Photography"],
    skillsWanted: ["Video Editing", "Motion Graphics", "After Effects"],
    rating: 4.5,
    availability: "evenings",
    isPublic: true,
    isOnline: false,
    lastSeen: "4 hours ago",
    bio: "Professional photographer looking to expand into video content creation.",
    completedSwaps: 22,
    joinedDate: "2023-02-10",
    badges: ["Creative", "Photo Expert"],
    matchScore: 80,
    isVerified: false,
    level: "intermediate",
  },

  // Beginner Level Users
  {
    id: "beginner-1",
    name: "Tom Wilson",
    email: "tom.wilson@email.com",
    role: "user",
    location: "Denver, CO",
    avatar: "/placeholder.svg?height=60&width=60",
    skillsOffered: ["Basic Excel", "Data Entry", "Microsoft Office"],
    skillsWanted: ["Python", "Data Analysis", "SQL"],
    rating: 4.2,
    availability: "weekdays",
    isPublic: true,
    isOnline: true,
    lastSeen: "15 minutes ago",
    bio: "Career changer looking to transition into tech. Excited to learn programming!",
    completedSwaps: 5,
    joinedDate: "2024-01-20",
    badges: ["New Member"],
    matchScore: 70,
    isVerified: false,
    level: "beginner",
  },
  {
    id: "beginner-2",
    name: "Maria Gonzalez",
    email: "maria.gonzalez@email.com",
    role: "user",
    location: "Miami, FL",
    avatar: "/placeholder.svg?height=60&width=60",
    skillsOffered: ["Spanish Language", "Translation", "Cultural Consulting"],
    skillsWanted: ["Web Design", "WordPress", "Basic Programming"],
    rating: 4.3,
    availability: "flexible",
    isPublic: true,
    isOnline: false,
    lastSeen: "1 day ago",
    bio: "Native Spanish speaker interested in learning web development to create bilingual websites.",
    completedSwaps: 8,
    joinedDate: "2024-02-05",
    badges: ["New Member", "Language Expert"],
    matchScore: 75,
    isVerified: false,
    level: "beginner",
  },
  {
    id: "beginner-3",
    name: "David Chang",
    email: "david.chang@email.com",
    role: "user",
    location: "Portland, OR",
    avatar: "/placeholder.svg?height=60&width=60",
    skillsOffered: ["Cooking", "Recipe Development", "Food Photography"],
    skillsWanted: ["Social Media Marketing", "Content Creation", "Business Basics"],
    rating: 4.1,
    availability: "weekends",
    isPublic: true,
    isOnline: true,
    lastSeen: "2 hours ago",
    bio: "Professional chef wanting to start a food blog and learn digital marketing.",
    completedSwaps: 3,
    joinedDate: "2024-03-01",
    badges: ["New Member", "Culinary Artist"],
    matchScore: 65,
    isVerified: false,
    level: "beginner",
  },

  // Specialized Users
  {
    id: "specialist-1",
    name: "Dr. Robert Kim",
    email: "robert.kim@email.com",
    role: "user",
    location: "Philadelphia, PA",
    avatar: "/placeholder.svg?height=60&width=60",
    skillsOffered: ["Medical Knowledge", "Healthcare Consulting", "Research Methods"],
    skillsWanted: ["Health Tech", "Mobile App Development", "Data Visualization"],
    rating: 4.8,
    availability: "weekday evenings",
    isPublic: true,
    isOnline: false,
    lastSeen: "6 hours ago",
    bio: "Practicing physician interested in health technology and digital health solutions.",
    completedSwaps: 12,
    joinedDate: "2023-09-15",
    badges: ["Medical Professional", "Verified", "Subject Expert"],
    matchScore: 82,
    isVerified: true,
    level: "expert",
  },
  {
    id: "specialist-2",
    name: "Prof. Angela Davis",
    email: "angela.davis@email.com",
    role: "user",
    location: "Cambridge, MA",
    avatar: "/placeholder.svg?height=60&width=60",
    skillsOffered: ["Academic Writing", "Research Methodology", "Literature Review"],
    skillsWanted: ["Online Course Creation", "Video Production", "Educational Technology"],
    rating: 4.9,
    availability: "afternoons",
    isPublic: true,
    isOnline: true,
    lastSeen: "now",
    bio: "University professor looking to create online courses and reach broader audiences.",
    completedSwaps: 19,
    joinedDate: "2023-08-20",
    badges: ["Professor", "Academic", "Verified", "Educator"],
    matchScore: 90,
    isVerified: true,
    level: "expert",
  }
];

// Test user credentials for login testing
export const testUserCredentials = [
  { email: "admin@skillxchange.com", password: "admin123", role: "admin" },
  { email: "tech.admin@skillxchange.com", password: "admin123", role: "admin" },
  { email: "jenny.mod@skillxchange.com", password: "mod123", role: "moderator" },
  { email: "emily.watson@email.com", password: "user123", role: "user" },
  { email: "marcus.chen@email.com", password: "user123", role: "user" },
  { email: "sarah.rodriguez@email.com", password: "user123", role: "user" },
  { email: "alex.thompson@email.com", password: "user123", role: "user" },
  { email: "jamie.park@email.com", password: "user123", role: "user" },
  { email: "lisa.kim@email.com", password: "user123", role: "user" },
  { email: "tom.wilson@email.com", password: "user123", role: "user" },
  { email: "maria.gonzalez@email.com", password: "user123", role: "user" },
  { email: "david.chang@email.com", password: "user123", role: "user" },
  { email: "robert.kim@email.com", password: "user123", role: "user" },
  { email: "angela.davis@email.com", password: "user123", role: "user" },
];

// Function to get user by email (for testing)
export const getUserByEmail = (email: string): UserProfile | undefined => {
  return mockUsers.find(user => user.email === email);
};

// Function to get users by role
export const getUsersByRole = (role: "admin" | "user" | "moderator"): UserProfile[] => {
  return mockUsers.filter(user => user.role === role);
};

// Function to get users by level
export const getUsersByLevel = (level: "beginner" | "intermediate" | "advanced" | "expert"): UserProfile[] => {
  return mockUsers.filter(user => user.level === level);
};

// Mock notifications with admin-specific ones
export const mockNotifications: Notification[] = [
  {
    id: "notif-1",
    type: "system",
    title: "Welcome to SkillXchange!",
    description: "Complete your profile to start connecting with other learners",
    timestamp: "1 hour ago",
    isRead: false,
  },
  {
    id: "notif-2",
    type: "request",
    title: "New Skill Exchange Request",
    description: "Sarah Rodriguez wants to exchange Graphic Design for your JavaScript skills",
    timestamp: "2 hours ago",
    isRead: false,
    userId: "advanced-1",
  },
  {
    id: "notif-3",
    type: "match",
    title: "Perfect Match Found!",
    description: "Dr. Emily Watson has skills you want and wants skills you have",
    timestamp: "4 hours ago",
    isRead: true,
    userId: "expert-1",
  },
  {
    id: "notif-4",
    type: "message",
    title: "New Message",
    description: "Marcus Chen sent you a message about system architecture",
    timestamp: "6 hours ago",
    isRead: true,
    userId: "expert-2",
  },
  {
    id: "admin-notif-1",
    type: "system",
    title: "Platform Update Required",
    description: "Security patch needs to be applied to the system",
    timestamp: "30 minutes ago",
    isRead: false,
  },
];

// Mock conversations
export const mockConversations: Conversation[] = [
  {
    id: "conv-1",
    userId: "expert-1",
    userName: "Dr. Emily Watson",
    userAvatar: "/placeholder.svg?height=40&width=40",
    lastMessage: "I'd be happy to help you with machine learning concepts!",
    lastMessageTime: "5 min ago",
    unreadCount: 2,
    isOnline: false,
  },
  {
    id: "conv-2",
    userId: "advanced-1",
    userName: "Sarah Rodriguez",
    userAvatar: "/placeholder.svg?height=40&width=40",
    lastMessage: "Let's schedule our design session for this weekend",
    lastMessageTime: "1 hour ago",
    unreadCount: 0,
    isOnline: false,
  },
  {
    id: "conv-3",
    userId: "intermediate-1",
    userName: "Jamie Park",
    userAvatar: "/placeholder.svg?height=40&width=40",
    lastMessage: "Thanks for the JavaScript tips!",
    lastMessageTime: "2 hours ago",
    unreadCount: 1,
    isOnline: true,
  },
];

// Export all existing mock data from the original file
export * from "./mock-data-fixed";
